<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, post, request } from '../api'

const page = ref<'overview'|'history'|'models'>('overview')
const metrics = ref<any>(null), modelStatus = ref<any>(null), conversations = ref<any[]>([])
const profiles = ref<any[]>([]), selected = ref<any>(null), detail = ref<any>(null)
const modalOpen = ref(false)
const filters = ref({ user_id:'', keyword:'', feature:'' }), notice = ref(''), saving = ref(false)
const form = ref<any>({ name:'', provider:'OpenAI Compatible', base_url:'https://api.deepseek.com', model:'deepseek-chat', api_key:'', timeout_seconds:30, json_mode:true, disable_thinking:false })
const title = computed(()=>({overview:'运营概览',history:'对话历史',models:'模型配置'}[page.value]))
const intentNames:Record<string,string>={recommendation:'案例推荐',filter:'多维筛选',statistics:'数据统计',qa:'比赛问答',greeting:'问候',mixed:'混合会话',unsupported:'越界拒绝',unknown:'未识别'}
const intentName=(value:string)=>intentNames[value]||value

async function loadOverview(){ metrics.value=await api('/ops/metrics'); metrics.value.recent_conversations=metrics.value.recent_conversations.map((x:any)=>({...x,feature:intentName(x.feature)})); metrics.value.feature_usage=Object.fromEntries(Object.entries(metrics.value.feature_usage).map(([key,value])=>[intentName(key),value])); modelStatus.value=await api('/ops/model-status') }
async function loadHistory(){ const q=new URLSearchParams(Object.entries(filters.value).filter(([,v])=>v)); const r:any=await api('/ops/conversations?'+q); conversations.value=r.items.map((x:any)=>({...x,feature:intentName(x.feature)})) }
async function loadProfiles(){ const r:any=await api('/ops/model-profiles'); profiles.value=r.items }
async function navigate(to:any){ page.value=to; detail.value=null; if(to==='overview')await loadOverview(); if(to==='history')await loadHistory(); if(to==='models')await loadProfiles() }
async function showConversation(id:string){ const r:any=await api('/ops/conversations/'+id); r.feature=intentName(r.feature); r.messages=r.messages.map((m:any)=>({...m,content:m.intent?`[${intentName(m.intent)}] ${m.content}`:m.content})); detail.value=r }
function editProfile(p?:any){ selected.value=p||null; modalOpen.value=true; form.value=p?{...p,api_key:''}:{name:'',provider:'OpenAI Compatible',base_url:'https://api.deepseek.com',model:'deepseek-chat',api_key:'',timeout_seconds:30,json_mode:true,disable_thinking:false} }
function closeProfile(){ modalOpen.value=false; selected.value=null }
async function save(){ saving.value=true; notice.value=''; try { if(selected.value) await request('/ops/model-profiles/'+selected.value.profile_id,{method:'PATCH',body:JSON.stringify(form.value)}); else await post('/ops/model-profiles',form.value); closeProfile(); await loadProfiles(); notice.value='配置已保存' } catch(e:any){notice.value=e.message} finally{saving.value=false} }
async function testProfile(p:any){ try{const r:any=await post(`/ops/model-profiles/${p.profile_id}/test`,{}); notice.value=r.success?`测试成功，延迟 ${Math.round(r.latency_ms)}ms`:`测试失败：${r.error||'连接异常'}`}catch(e:any){notice.value=e.message} await loadProfiles() }
async function activate(p:any){ if(!confirm(`确认激活“${p.name}”吗？`))return; try{await post(`/ops/model-profiles/${p.profile_id}/activate`,{});notice.value='已切换活动模型'}catch(e:any){notice.value=e.message} await loadProfiles(); await loadOverview() }
async function removeProfile(p:any){ if(!confirm(`删除“${p.name}”？`))return; try{await request(`/ops/model-profiles/${p.profile_id}`,{method:'DELETE'});notice.value='配置已删除'}catch(e:any){notice.value=e.message} await loadProfiles() }
onMounted(loadOverview)
</script>

<template>
  <div class="ops-shell">
    <aside class="ops-sidebar"><div class="ops-brand"><span>尽</span><div><b>尽调助手</b><small>运营管理平台</small></div></div><nav><button :class="{active:page==='overview'}" @click="navigate('overview')">▦ 运营概览</button><button :class="{active:page==='history'}" @click="navigate('history')">◫ 对话历史</button><button :class="{active:page==='models'}" @click="navigate('models')">⚙ 模型配置</button></nav><div class="ops-version">内部服务 · v1.0</div></aside>
    <main class="ops-main"><header class="ops-header"><div><h1>{{title}}</h1><p>尽调报告智能推荐服务运营工作台</p></div><span class="status-dot">● 服务运行中</span></header><div class="risk-banner">⚠ 应用自身不处理登录；公网部署必须由 Nginx 等可信网关保护运营页面和运营接口。</div>
      <section v-if="page==='overview' && metrics" class="ops-content"><div class="metric-grid"><article><small>用户数</small><b>{{metrics.users}}</b><em>累计访问用户</em></article><article><small>会话数</small><b>{{metrics.sessions}}</b><em>全部功能会话</em></article><article><small>消息数</small><b>{{metrics.messages}}</b><em>用户与助手消息</em></article><article class="danger"><small>模型调用失败</small><b>{{metrics.model_failures}}</b><em>需关注异常</em></article></div><div class="ops-columns"><section class="ops-card"><h2>功能使用情况</h2><div v-for="(count,name) in metrics.feature_usage" :key="name" class="usage-row"><span>{{name}}</span><i><u :style="{width:Math.min(100,Number(count)*12)+'%'}"></u></i><b>{{count}}</b></div></section><section class="ops-card model-health"><h2>当前激活模型</h2><div class="model-logo">AI</div><b>{{modelStatus?.profile_name || '环境变量配置'}}</b><p>{{modelStatus?.model || '未配置模型'}}</p><span :class="['health-pill',modelStatus?.healthy?'ok':'warn']">{{modelStatus?.healthy?'健康':'未就绪'}}</span><button @click="navigate('models')">管理模型配置</button></section></div><section class="ops-card"><div class="card-heading"><h2>最近会话</h2><button @click="navigate('history')">查看全部 →</button></div><table><thead><tr><th>会话标题</th><th>用户</th><th>功能</th><th>消息数</th><th>更新时间</th></tr></thead><tbody><tr v-for="x in metrics.recent_conversations" :key="x.session_id"><td>{{x.title}}</td><td>{{x.user_id}}</td><td><span class="tag">{{x.feature}}</span></td><td>{{x.message_count}}</td><td>{{x.updated_at}}</td></tr></tbody></table></section></section>
      <section v-if="page==='history'" class="ops-content"><div class="filter-bar"><input v-model="filters.user_id" placeholder="用户 ID"/><input v-model="filters.keyword" placeholder="搜索会话或消息关键词" @keyup.enter="loadHistory"/><select v-model="filters.feature"><option value="">全部功能</option><option value="recommendation">智能推荐</option><option value="filter">多维筛选</option><option value="statistics">数据统计</option><option value="qa">比赛问答</option><option value="mixed">混合会话</option></select><button class="ops-primary" @click="loadHistory">查询</button></div><section class="ops-card"><table><thead><tr><th>会话标题</th><th>用户 ID</th><th>功能</th><th>消息数</th><th>开始时间</th><th>更新时间</th><th></th></tr></thead><tbody><tr v-for="x in conversations" :key="x.session_id"><td><b>{{x.title}}</b></td><td>{{x.user_id}}</td><td><span class="tag">{{x.feature}}</span></td><td>{{x.message_count}}</td><td>{{x.created_at}}</td><td>{{x.updated_at}}</td><td><button class="link-btn" @click="showConversation(x.session_id)">查看详情</button></td></tr></tbody></table><div v-if="!conversations.length" class="empty-state">暂无符合条件的会话</div></section></section>
      <section v-if="page==='models'" class="ops-content"><div class="card-heading page-action"><div><h2>模型配置</h2><p>保存多套 OpenAI 兼容模型配置，测试通过后可热切换。</p></div><button class="ops-primary" @click="editProfile()">＋ 新建配置</button></div><p v-if="notice" class="ops-notice">{{notice}}</p><div class="profile-grid"><article v-for="p in profiles" :key="p.profile_id" :class="['profile-card',{active:p.is_active}]"><div class="profile-top"><span class="model-logo small">AI</span><div><h3>{{p.name}}</h3><p>{{p.provider}}</p></div><span v-if="p.is_active" class="active-badge">当前激活</span></div><dl><dt>模型</dt><dd>{{p.model}}</dd><dt>地址</dt><dd>{{p.base_url}}</dd><dt>密钥</dt><dd>{{p.api_key_masked || '未设置'}}</dd><dt>最近测试</dt><dd><span :class="['test-status',p.last_test_status]">{{p.last_test_status || '未测试'}}</span> {{p.last_test_latency_ms?Math.round(p.last_test_latency_ms)+'ms':''}}</dd></dl><div class="profile-actions"><button @click="editProfile(p)">编辑</button><button @click="testProfile(p)">测试</button><button v-if="!p.is_active" class="activate" @click="activate(p)">激活</button><button v-if="!p.is_active" class="delete" @click="removeProfile(p)">删除</button></div></article><div v-if="!profiles.length" class="empty-profile">尚未创建数据库模型配置，服务当前使用环境变量配置。</div></div></section>
    </main>
    <div v-if="detail" class="ops-drawer-mask" @click.self="detail=null"><aside class="ops-drawer"><div class="drawer-title"><div><h2>{{detail.title}}</h2><p>{{detail.user_id}} · {{detail.feature}}</p></div><button @click="detail=null">×</button></div><div class="tag-cloud"><span v-for="t in detail.tags" :key="t.name">{{t.name}}：{{t.value}}</span></div><div class="timeline"><article v-for="m in detail.messages" :key="m.id" :class="m.role"><small>{{m.role==='user'?'用户':'助手'}} · {{m.created_at}}</small><p>{{m.content}}</p><div v-if="m.payload?.recommendations" class="payload-summary">含 {{m.payload.recommendations.length}} 条推荐结果</div></article></div></aside></div>
    <div v-if="modalOpen" class="modal-mask" @click.self="closeProfile"><form class="profile-modal" @submit.prevent="save"><div class="drawer-title"><h2>{{selected?'编辑模型配置':'新建模型配置'}}</h2><button type="button" @click="closeProfile">×</button></div><label>配置名称<input v-model="form.name" required/></label><label>提供方<input v-model="form.provider" required/></label><label>Base URL<input v-model="form.base_url" required/></label><label>模型名称<input v-model="form.model" required/></label><label>API Key<input v-model="form.api_key" type="password" :placeholder="selected?'留空则保留原密钥':'请输入 API Key'"/></label><label>请求超时（秒）<input v-model.number="form.timeout_seconds" type="number" min="1" max="300"/></label><div class="checks"><label><input v-model="form.json_mode" type="checkbox"/> JSON Output</label><label><input v-model="form.disable_thinking" type="checkbox"/> 关闭思考模式</label></div><button class="ops-primary submit" :disabled="saving">{{saving?'保存中…':'保存配置'}}</button></form></div>
  </div>
</template>
